export const initialGroups = [
  {
    title: "React Hooks Avançados",
    members: 18,
    time: "Noite",
    description: "Estudo aprofundado de hooks customizados e otimização",
    tags: ["React", "Avançado"],
    createdByCurrentMentor: true,
  },
  {
    title: "JavaScript para Iniciantes",
    members: 24,
    time: "Tarde",
    description: "Fundamentos da linguagem e primeiros projetos",
    tags: ["JavaScript", "Iniciante"],
    createdByCurrentMentor: false,
  },
  {
    title: "Node.js e APIs REST",
    members: 15,
    time: "Noite",
    description: "Desenvolvimento de APIs escaláveis com Express",
    tags: ["Node.js", "Intermediário"],
    createdByCurrentMentor: true,
  },
  {
    title: "Python para Data Science",
    members: 22,
    time: "Fins de semana",
    description: "Pandas, NumPy e visualização de dados",
    tags: ["Python", "Intermediário"],
    createdByCurrentMentor: false,
  },
  {
    title: "TypeScript do Zero",
    members: 19,
    time: "Manhã",
    description: "Tipagem estática e boas práticas",
    tags: ["TypeScript", "Iniciante"],
    createdByCurrentMentor: false,
  },
  {
    title: "Java Spring Boot",
    members: 12,
    time: "Noite",
    description: "Desenvolvimento enterprise com Spring Framework",
    tags: ["Java", "Avançado"],
    createdByCurrentMentor: false,
  },
  {
    title: "Vue.js Essencial",
    members: 16,
    time: "Tarde",
    description: "Composition API e gerenciamento de estado",
    tags: ["Vue", "Intermediário"],
    createdByCurrentMentor: false,
  },
  {
    title: "Algoritmos e Estruturas de Dados",
    members: 28,
    time: "Fins de semana",
    description: "Preparação para entrevistas técnicas",
    tags: ["JavaScript", "Intermediário"],
    createdByCurrentMentor: false,
  },
];
