export const mentors = [
  {
    name: "Ana Costa",
    role: "Frontend Development",
    tags: ["React", "TypeScript", "Next.js"],
    rating: "4.8 / 5.0",
    sessions: "45 sessões realizadas",
    availability: "Noites e fins de semana",
    channel: "Google Meet ou Discord",
    format: "Sessões individuais de 45 minutos",
    instructions: "Envie sua principal dúvida e links do projeto antes da conversa.",
  },
  {
    name: "Carlos Mendes",
    role: "Backend e DevOps",
    tags: ["Node.js", "PostgreSQL", "Docker"],
    rating: "4.9 / 5.0",
    sessions: "62 sessões realizadas",
    availability: "Tardes",
    channel: "Google Meet",
    format: "Revisão de arquitetura e pareamento",
    instructions: "Informe o contexto da API ou infraestrutura que deseja revisar.",
  },
  {
    name: "Beatriz Lima",
    role: "Full Stack e Cloud",
    tags: ["JavaScript", "React", "AWS"],
    rating: "4.7 / 5.0",
    sessions: "38 sessões realizadas",
    availability: "Manhãs",
    channel: "Discord",
    format: "Sessão de dúvidas e plano de estudos",
    instructions: "Liste os temas de cloud ou full stack que quer priorizar.",
  },
  {
    name: "Ricardo Santos",
    role: "Data Science e ML",
    tags: ["Python", "Django", "Machine Learning"],
    rating: "4.9 / 5.0",
    sessions: "51 sessões realizadas",
    availability: "Noites",
    channel: "Google Meet",
    format: "Mentoria guiada por notebook ou projeto",
    instructions: "Prepare o dataset ou problema de machine learning que deseja discutir.",
  },
  {
    name: "Juliana Rocha",
    role: "Frontend e UI/UX",
    tags: ["Vue", "Nuxt", "Tailwind CSS"],
    rating: "4.6 / 5.0",
    sessions: "29 sessões realizadas",
    availability: "Fins de semana",
    channel: "Discord ou Meet",
    format: "Análise de interface e carreira",
    instructions: "Compartilhe referências, protótipos ou dúvidas de UI/UX.",
  },
  {
    name: "Fernando Alves",
    role: "Arquitetura Enterprise",
    tags: ["Java", "Spring Boot", "Microservices"],
    rating: "4.8 / 5.0",
    sessions: "47 sessões realizadas",
    availability: "Tardes e noites",
    channel: "Google Meet",
    format: "Discussão técnica e desenho de solução",
    instructions: "Descreva o problema de arquitetura antes da sessão.",
  },
  {
    name: "Helena Martins",
    role: "Banco de Dados",
    tags: ["PostgreSQL", "Node.js", "Docker"],
    rating: "4.8 / 5.0",
    sessions: "33 sessões realizadas",
    availability: "Noites",
    channel: "Google Meet",
    format: "Revisão de modelagem e queries",
    instructions: "Envie schema, consultas e objetivo da otimização.",
  },
  {
    name: "Diego Teles",
    role: "Frontend Angular",
    tags: ["Angular", "TypeScript", "RxJS"],
    rating: "4.7 / 5.0",
    sessions: "26 sessões realizadas",
    availability: "Manhãs",
    channel: "Discord",
    format: "Sessão guiada por projeto",
    instructions: "Compartilhe componentes ou fluxos que deseja revisar.",
  },
  {
    name: "Camila Nunes",
    role: "Backend com Go",
    tags: ["Go", "APIs", "Microservices"],
    rating: "4.9 / 5.0",
    sessions: "41 sessões realizadas",
    availability: "Fins de semana",
    channel: "Google Meet",
    format: "Discussão técnica e plano de evolução",
    instructions: "Descreva o serviço ou arquitetura que quer construir.",
  },
  {
    name: "Roberto Silva",
    role: "Performance Backend",
    tags: ["Node.js", "PostgreSQL", "Redis"],
    rating: "4.8 / 5.0",
    sessions: "39 sessões realizadas",
    availability: "Tardes",
    channel: "Google Meet",
    format: "Análise de gargalos e plano de ação",
    instructions: "Envie métricas, logs ou trechos relevantes do backend.",
  },
  {
    name: "Fernanda Lima",
    role: "React e Estado Global",
    tags: ["React", "JavaScript", "TypeScript"],
    rating: "4.7 / 5.0",
    sessions: "35 sessões realizadas",
    availability: "Noites",
    channel: "Discord ou Meet",
    format: "Mentoria de arquitetura frontend",
    instructions: "Liste dúvidas de estado, componentes e organização.",
  },
  {
    name: "Bruno Costa",
    role: "APIs REST",
    tags: ["Node.js", "Express", "Docker"],
    rating: "4.6 / 5.0",
    sessions: "31 sessões realizadas",
    availability: "Tardes e noites",
    channel: "Google Meet",
    format: "Code review e desenho de API",
    instructions: "Envie endpoints, rotas ou contrato da API.",
  },
];

export const students = [
  { name: "Patrícia Melo", role: "Frontend Development", tags: ["React", "TypeScript", "Next.js"], sessions: 45 },
  { name: "Ronaldo Lima", role: "Backend e DevOps", tags: ["Node.js", "PostgreSQL", "Docker"], sessions: 62 },
  { name: "Rogério Marques", role: "Backend e DevOps", tags: ["Node.js", "PostgreSQL", "Docker"], sessions: 32 },
  { name: "Charles Mendes", role: "Backend e DevOps", tags: ["Node.js", "PostgreSQL", "Docker"], sessions: 56 },
  { name: "Rogério Ceni", role: "Backend e DevOps", tags: ["Node.js", "PostgreSQL", "Docker"], sessions: 28 },
  { name: "Diego Teles", role: "Backend e DevOps", tags: ["Node.js", "PostgreSQL", "Docker"], sessions: 34 },
];

export const mentorshipStatus = {
  REQUESTED: {
    label: "Solicitada",
    description: "Aguardando aprovação do mentor.",
  },
  APPROVED: {
    label: "Aprovada",
    description: "O mentor aprovou sua solicitação. Combine os detalhes pelo canal informado.",
  },
  COMPLETED: {
    label: "Concluída",
    description: "Mentoria finalizada.",
  },
  CANCELLED: {
    label: "Cancelada",
    description: "Solicitação cancelada ou recusada.",
  },
};

export const initialMentorships = [
  {
    mentorName: "Carlos Mendes",
    role: "Backend e DevOps",
    status: "APPROVED",
    channel: "Google Meet",
    availability: "Tardes",
    format: "Revisão de arquitetura e pareamento",
  },
];

export const initialMentorRequests = [
  {
    id: "request-1",
    studentName: "João Silva",
    topic: "React Hooks e organização de componentes",
    status: "REQUESTED",
    message: "Quero revisar um projeto pessoal e entender melhor quando criar hooks customizados.",
  },
  {
    id: "request-2",
    studentName: "Mariana Alves",
    topic: "TypeScript no frontend",
    status: "REQUESTED",
    message: "Tenho dúvidas sobre tipagem de props e chamadas de API.",
  },
  {
    id: "request-3",
    studentName: "Rafael Costa",
    topic: "PostgreSQL e índices",
    status: "REQUESTED",
    message: "Preciso entender como identificar queries lentas e escolher índices.",
  },
  {
    id: "request-4",
    studentName: "Beatriz Lima",
    topic: "Deploy com Docker",
    status: "REQUESTED",
    message: "Quero revisar meu compose e entender variáveis de ambiente.",
  },
  {
    id: "request-5",
    studentName: "Bruno Costa",
    topic: "APIs REST",
    status: "REQUESTED",
    message: "Tenho dúvidas sobre organização de controllers e services.",
  },
  {
    id: "request-6",
    studentName: "Sofia Mendes",
    topic: "React Context",
    status: "REQUESTED",
    message: "Quero entender quando Context substitui uma biblioteca de estado.",
  },
  {
    id: "request-7",
    studentName: "Roberto Silva",
    topic: "Node.js performance",
    status: "REQUESTED",
    message: "Preciso revisar gargalos em chamadas assíncronas.",
  },
  {
    id: "request-8",
    studentName: "Fernanda Lima",
    topic: "TypeScript avançado",
    status: "REQUESTED",
    message: "Quero melhorar tipos reutilizáveis no frontend.",
  },
  {
    id: "request-9",
    studentName: "Helena Martins",
    topic: "Django APIs",
    status: "REQUESTED",
    message: "Tenho dúvidas sobre autenticação e permissões.",
  },
  {
    id: "request-10",
    studentName: "Diego Teles",
    topic: "Angular services",
    status: "REQUESTED",
    message: "Preciso organizar services e interceptors.",
  },
  {
    id: "request-11",
    studentName: "Camila Nunes",
    topic: "Go web",
    status: "REQUESTED",
    message: "Quero entender estrutura de handlers e middlewares.",
  },
  {
    id: "request-12",
    studentName: "Patrícia Melo",
    topic: "Next.js",
    status: "REQUESTED",
    message: "Tenho dúvidas sobre rotas, SSR e componentes.",
  },
];

export function ratingToNumber(rating) {
  return Number.parseFloat(String(rating).split(" ")[0]) || 0;
}
